### ISSUE TITLE
Drop In replacement for spatie/data-transfer-object

### ISSUE THREAD

**Issue by wucherpfennig** [Dgame/php-dto#6]
As the spatie package is deprecated do you think you could modify your package to be used as drop in replacement?

I really like your approach but I am missing some functionality as `all, except, only, toArray` etc.

BR wucherpfennig

**Comment by Dgame** [comment]
I would love to. Any chances of getting help with that? What do you need, what is missing or should be different?
What I understand is, that you are missing four functions (`all`, `except`, `only`, `toArray`) but what else? 🙂

**Comment by wucherpfennig** [comment]
Well those were the functions I have used with the package. 😉

I have to admit that this request has somehow less importance to me as I have replicated most of the spatie package using symfony' serializer. Which is working great so far.
